# Matematické a statistické značení a vzorce {.unnumbered}

Přehled používá stejné symboly jako výklad. Alternativy slouží k orientaci v jiné literatuře; ve výpočtech je nestřídáme. Vyhledávat lze i podle slovního významu.

::: {.reference-table}
<table id="notation-table"><caption>Přehled zavedeného značení a vzorců</caption><thead><tr><th scope="col">Značení</th><th scope="col">Význam a prvky zápisu</th><th scope="col">Výpočetní vztah nebo příklad</th><th scope="col">Alternativy</th><th scope="col">Výklad</th></tr></thead><tbody>
<tr id="znak-n"><th scope="row">$n$</th><td>Rozsah souboru: počet případů zahrnutých do konkrétního výpočtu.</td><td>$n=\sum_{j=1}^{k}f_j$</td><td>N v jiné literatuře; zde používáme malé n.</td><td><a href="kapitola_02.html#sec-co-pocitame">Výklad</a></td></tr>
<tr id="znak-i"><th scope="row">$i$</th><td>Index jednotlivého pozorování; neoznačuje kategorii ani skupinu.</td><td>$i=1,\ldots,n$ pro n zahrnutých pozorování.</td><td>Písmeno indexu závisí na konvenci; zde i pro pozorování.</td><td><a href="kapitola_02.html#sec-relativni-cetnost">Výklad</a></td></tr>
<tr id="znak-j"><th scope="row">$j$</th><td>Index kategorie, hodnoty, intervalu nebo skupiny.</td><td>$j=1,\ldots,k$ pro k kategorií.</td><td>i v jiné literatuře; zde j pro kategorie a skupiny.</td><td><a href="kapitola_02.html#sec-relativni-cetnost">Výklad</a></td></tr>
<tr id="znak-k"><th scope="row">$k$</th><td>Počet kategorií, jednotlivých hodnot nebo intervalů v dané tabulce.</td><td>$k=4$</td><td>Jiná literatura může používat jiná písmena.</td><td><a href="kapitola_02.html#sec-sumace">Výklad</a></td></tr>
<tr id="znak-f"><th scope="row">$f_j$</th><td>Absolutní četnost v kategorii j.</td><td>$f_2=2$</td><td>n_j; zde f_j.</td><td><a href="kapitola_02.html#sec-relativni-cetnost">Výklad</a></td></tr>
<tr id="znak-p"><th scope="row">$p_j$</th><td>Relativní četnost v kategorii j; n je počet zahrnutých případů.</td><td>$p_j=\frac{f_j}{n}$</td><td>r_j, f_j v některých zdrojích; zde p_j. Nejde zde o p-hodnotu.</td><td><a href="kapitola_02.html#sec-relativni-cetnost">Výklad</a></td></tr>
<tr id="znak-kum-f"><th scope="row">$f_{\mathrm{kum},j}$</th><td>Kumulativní absolutní četnost: počet až po kategorii j včetně. Část kum je slovní připomínka.</td><td>$f_{\mathrm{kum},j}=f_1+\cdots+f_j$</td><td>F_j; zde malé f s indexem kum.</td><td><a href="kapitola_02.html#sec-kumulativni-cetnosti">Výklad</a></td></tr>
<tr id="znak-kum-p"><th scope="row">$p_{\mathrm{kum},j}$</th><td>Kumulativní relativní četnost: podíl až po kategorii j včetně.</td><td>$p_{\mathrm{kum},j}=\frac{f_{\mathrm{kum},j}}{n}$</td><td>P_j; zde malé p s indexem kum.</td><td><a href="kapitola_02.html#sec-kumulativni-cetnosti">Výklad</a></td></tr>
<tr id="znak-sumace"><th scope="row">$\sum_{j=1}^{k}f_j$</th><td>Sumace (summation): sčítáme členy f_j pro index j od dolní meze 1 do horní meze k. Sigma zde je operátor.</td><td>$\sum_{j=1}^{4}f_j=f_1+f_2+f_3+f_4$</td><td>Rozepsaný součet; sigma není populační parametr.</td><td><a href="kapitola_02.html#sec-sumace">Výklad</a></td></tr>
<tr id="znak-soucet"><th scope="row">$+$</th><td>Sčítání; členy úplné četnostní tabulky pokrývají každý případ právě jednou.</td><td>$1+2+2+1=6$</td><td>Zkráceně znak sumace.</td><td><a href="kapitola_02.html#sec-sumace">Výklad</a></td></tr>
<tr id="znak-deleni"><th scope="row">$\frac{f_j}{n}$</th><td>Zlomková čára znamená dělení. Čitatel je nahoře, jmenovatel dole.</td><td>$\frac{2}{6}=0{,}333\ldots$</td><td>2/6; v Excelu lomítko /.</td><td><a href="kapitola_02.html#sec-relativni-cetnost">Výklad</a></td></tr>
<tr id="znak-procento"><th scope="row">$\%$</th><td>Procento znamená jednu setinu. Podíl 1 odpovídá 100 %.</td><td>$0{,}25=25\,\%$</td><td>Procentní vyjádření téhož podílu.</td><td><a href="kapitola_02.html#sec-relativni-cetnost">Výklad</a></td></tr>
<tr id="znak-tecky"><th scope="row">$\ldots,\;\cdots$</th><td>Tři tečky zastupují pokračování pravidla: číslice desetinného rozvoje nebo další členy součtu.</td><td>$f_1+\cdots+f_4=f_1+f_2+f_3+f_4$</td><td>Nejde o chybějící údaj.</td><td><a href="kapitola_02.html#sec-kumulativni-cetnosti">Výklad</a></td></tr>
<tr id="znak-nasobeni"><th scope="row">$\times$</th><td>Násobení, například při porovnání ploch obdélníků.</td><td>$10\times1=5\times2=10$</td><td>Středová tečka v jiných textech; v Excelu hvězdička.</td><td><a href="kapitola_02.html#sec-volba-intervalu">Výklad</a></td></tr>
<tr id="vztah-stred-intervalu"><th scope="row">Střed intervalu</th><td>Dolní mez plus polovina rozdílu horní a dolní meze. Závorka určuje, že nejprve odečteme meze.</td><td>$6+(7-6)/2=6{,}5$; všechny hodnoty jsou v hodinách, dělíme dvěma.</td><td>Stejný výsledek dává součet mezí dělený dvěma: $(6+7)/2=6{,}5$.</td><td><a href="kapitola_02.html#sec-polygon-cetnosti">Výklad</a></td></tr>
<tr id="znak-xi"><th scope="row">$x_i$</th><td>Hodnota proměnné u i-tého pozorování; i je index, n počet platných hodnot.</td><td>$x_1=4$ minuty.</td><td>x, X v jiných textech; zde malé kurzivní x.</td><td><a href="kapitola_03.html#sec-prumer">Výklad</a></td></tr>
<tr id="znak-serazene"><th scope="row">$x_{(i)}$</th><td>i-tá hodnota po seřazení; závorky v indexu značí pořadí, nikoli původní číslo případu.</td><td>$x_{(1)}$ je minimum, $x_{(n)}$ maximum.</td><td>Pořadová statistika.</td><td><a href="kapitola_03.html#sec-vypocet-kvantilu">Výklad</a></td></tr>
<tr id="znak-m"><th scope="row">$m$</th><td>Výběrový aritmetický průměr; x_i jsou hodnoty a n jejich počet.</td><td>$m=\frac{1}{n}\sum_{i=1}^{n}x_i$</td><td>M, x s pruhem; zde malé kurzivní m.</td><td><a href="kapitola_03.html#sec-prumer">Výklad</a></td></tr>
<tr id="znak-median"><th scope="row">$\tilde{x}$</th><td>Medián; vlnovka nad x označuje prostřední polohu seřazených hodnot.</td><td>Pro 4, 5, 5, 6, 10 je $\tilde{x}=5$.</td><td>Mdn, Me; zde x s vlnovkou.</td><td><a href="kapitola_03.html#sec-median">Výklad</a></td></tr>
<tr id="znak-qp"><th scope="row">$q_p$</th><td>Kvantil na úrovni p; p je podíl od 0 do 1, nikoli číslo procenta.</td><td>Pozice $1+(n-1)p$ a interpolace mezi sousedy; $q_{0{,}25}=5$.</td><td>Q₁, Q₃ pro kvartily; zde malé q s úrovní v indexu.</td><td><a href="kapitola_03.html#sec-vypocet-kvantilu">Výklad</a></td></tr>
<tr id="vztah-uroven-kvantilu"><th scope="row">Úroveň kvantilu přiřazená pozici</th><td>i je pozice v seřazené řadě, n počet hodnot. Platí pro n &gt; 1 v konvenci PERCENTIL.INC; nejde o skutečný kumulativní podíl.</td><td>$p=\frac{i-1}{n-1}$; třetí z jedenácti hodnot: $p=2/10=0{,}2$.</td><td>Jiné konvence kvantilů přiřazují jiné úrovně.</td><td><a href="kapitola_03.html#sec-vypocet-kvantilu">Výklad</a></td></tr>
<tr id="vztah-interpolace"><th scope="row">Lineární interpolace kvantilu</th><td>Pozice je $1+(n-1)p$. Pro necelou pozici je i její celá část, $x_{(i)}$ nižší a $x_{(i+1)}$ vyšší sousední hodnota; pozice − i je část cesty mezi nimi. Při celočíselné pozici vezmeme přímo danou hodnotu.</td><td>$q_p=x_{(i)}+(\text{pozice}-i)\times(x_{(i+1)}-x_{(i)})$; pro jedenáct časů v příkladu $q_{0{,}17}=5+0{,}7\times(7-5)=6{,}4$ minuty.</td><td>Nižší hodnota plus odpovídající část rozdílu; konvence PERCENTIL.INC.</td><td><a href="kapitola_03.html#sec-vypocet-kvantilu">Výklad</a></td></tr>
<tr id="vztah-percentilove-poradi"><th scope="row">Percentilové pořadí</th><td>Počet menších hodnot plus všechny shody (inkluzivní), žádné shody (exkluzivní) nebo polovina shod (kompromisní); výsledek vydělíme počtem n a vynásobíme 100.</td><td>Pro 5 v souboru 4, 5, 5, 6, 10: inkluzivně $(1+2)/5\times100=60$, exkluzivně $1/5\times100=20$, kompromisně $(1+2/2)/5\times100=40$.</td><td>Různé konvence zacházení se shodami; nejde o úrovně kvantilů PERCENTIL.INC.</td><td><a href="kapitola_03.html#sec-percentilove-poradi">Výklad</a></td></tr>
<tr id="znak-rozpeti"><th scope="row">Variační rozpětí</th><td>Rozdíl maxima a minima.</td><td>$x_{(n)}-x_{(1)}$; zde $10-4=6$ minut.</td><td>R, range; bez nové písmenné zkratky.</td><td><a href="kapitola_03.html#sec-rozpeti">Výklad</a></td></tr>
<tr id="znak-iqr"><th scope="row">Mezikvartilové rozpětí</th><td>Rozdíl horního a dolního kvartilu.</td><td>$q_{0{,}75}-q_{0{,}25}$; zde $6-5=1$ minuta.</td><td>IQR; slovně, bez samostatného symbolu ve výkladu.</td><td><a href="kapitola_03.html#sec-rozpeti">Výklad</a></td></tr>
<tr id="znak-absolutni"><th scope="row">$|x_i-m|$</th><td>Absolutní hodnota odchylky; svislé čáry odstraňují záporné znaménko.</td><td>$|4-6|=|-2|=2$</td><td>abs; Excel ABS.</td><td><a href="kapitola_03.html#sec-prumerna-absolutni">Výklad</a></td></tr>
<tr id="znak-aad"><th scope="row">Průměrná absolutní odchylka</th><td>n: počet hodnot; m: průměr; absolutní odchylky průměrujeme.</td><td>$\frac{1}{n}\sum_{i=1}^{n}|x_i-m|$; zde $8/5=1{,}6$.</td><td>AAD; někdy MAD (pozor na záměnu s mediánovou variantou).</td><td><a href="kapitola_03.html#sec-prumerna-absolutni">Výklad</a></td></tr>
<tr id="znak-ctverec"><th scope="row">$(x_i-m)^2$</th><td>Druhá mocnina neboli čtverec: odchylku násobíme sebou samou.</td><td>$(-2)^2=(-2)\times(-2)=4$</td><td>Excel B2^2.</td><td><a href="kapitola_03.html#sec-rozptyl">Výklad</a></td></tr>
<tr id="znak-soucet-ctvercu"><th scope="row">$\sum_{i=1}^{n}(x_i-m)^2$</th><td>Součet čtverců odchylek všech n hodnot od průměru m.</td><td>$4+1+1+0+16=22$ min².</td><td>SS v odborné literatuře; zde rozepsaný vztah.</td><td><a href="kapitola_03.html#sec-rozptyl">Výklad</a></td></tr>
<tr id="znak-rozptyl-n"><th scope="row">Rozptyl s dělením n</th><td>Popis průměrného čtverce odchylky v pozorovaném souboru.</td><td>$\frac{1}{n}\sum_{i=1}^{n}(x_i-m)^2$; zde $22/5=4{,}4$ min².</td><td>Excel VAR.P; není totéž s².</td><td><a href="kapitola_03.html#sec-rozptyl">Výklad</a></td></tr>
<tr id="znak-s2"><th scope="row">$s^2$</th><td>Výběrový rozptyl; jmenovatel n − 1 souvisí s odhadováním populačního rozptylu.</td><td>$s^2=\frac{\sum_{i=1}^{n}(x_i-m)^2}{n-1}$; pro n &gt; 1.</td><td>VAR, V v jiných zdrojích; zde s².</td><td><a href="kapitola_03.html#sec-rozptyl">Výklad</a></td></tr>
<tr id="znak-odmocnina"><th scope="row">$\sqrt{a}$</th><td>Druhá odmocnina nezáporného čísla a: nezáporné číslo, jehož čtverec je a.</td><td>$\sqrt{4}=2$, protože $2^2=4$.</td><td>sqrt; Excel ODMOCNINA.</td><td><a href="kapitola_03.html#sec-smerodatna-odchylka">Výklad</a></td></tr>
<tr id="znak-s"><th scope="row">$s$</th><td>Výběrová směrodatná odchylka v původních jednotkách.</td><td>$s=\sqrt{s^2}$; zde $\sqrt{5{,}5}\doteq2{,}35$ minuty.</td><td>SD; zde malé kurzivní s.</td><td><a href="kapitola_03.html#sec-smerodatna-odchylka">Výklad</a></td></tr>
<tr id="znak-priblizne"><th scope="row">$\doteq$</th><td>Přibližná rovnost, například po zaokrouhlení konečného výsledku.</td><td>$\sqrt{5{,}5}\doteq2{,}35$</td><td>≈; přesnou rovnost značí =.</td><td><a href="kapitola_03.html#sec-smerodatna-odchylka">Výklad</a></td></tr>
<tr id="znak-mad"><th scope="row">Medián absolutních odchylek od mediánu</th><td>Nejprve medián dat, pak vzdálenost každé hodnoty od něj, nakonec medián těchto vzdáleností.</td><td>4, 5, 5, 6, 10 → medián 5 → vzdálenosti 1, 0, 0, 1, 5 → medián 1.</td><td>MAD; zde bez koeficientu 1,4826.</td><td><a href="kapitola_03.html#sec-median-absolutnich">Výklad</a></td></tr>
<tr id="znak-boxplot"><th scope="row">Meze pro vousy krabicového grafu</th><td>Od dolního kvartilu odečteme a k hornímu přičteme 1,5násobek mezikvartilového rozpětí.</td><td>$5-1{,}5\times1=3{,}5$; $6+1{,}5\times1=7{,}5$. Vousy končí na hodnotách 4 a 6.</td><td>Fences nejsou koncové hodnoty vousů.</td><td><a href="kapitola_03.html#sec-boxplot">Výklad</a></td></tr>
<tr id="znak-log2"><th scope="row">$\log_2 p$</th><td>Logaritmus kladného p o základu 2: mocnina, na kterou umocníme dvojku, abychom dostali p.</td><td>$\log_2(1/4)=-2$, protože $2^{-2}=1/4$.</td><td>log(p, 2); Excel LOGZ(p;2).</td><td><a href="kapitola_03.html#sec-entropie">Výklad</a></td></tr>
<tr id="znak-h"><th scope="row">$h$</th><td>Entropie pozorovaných podílů; p_j je podíl j-té kategorie, k jejich počet. Příspěvek nulového podílu bereme jako 0.</td><td>$h=-\sum_{j=1}^{k}p_j\log_2 p_j$; jednotka bit.</td><td>H v teorii informace; zde malé kurzivní h pro popis dat.</td><td><a href="kapitola_03.html#sec-entropie">Výklad</a></td></tr>
<tr id="znak-mocniny34"><th scope="row">$(x_i-m)^3$, $(x_i-m)^4$</th><td>Třetí a čtvrtá mocnina odchylky: násobení třikrát, resp. čtyřikrát sebou samou.</td><td>$(-2)^3=-8$, $(-2)^4=16$.</td><td>Excel B2^3 a B2^4.</td><td><a href="kapitola_03.html#sec-momenty">Výklad</a></td></tr>
<tr id="znak-g1"><th scope="row">$g_1$</th><td>Základní momentová šikmost; čitatel je průměr třetích mocnin odchylek, jmenovatel třetí mocnina odmocněného průměru čtverců s dělením n.</td><td>$g_1=\frac{\frac1n\sum_{i=1}^{n}(x_i-m)^3}{(\sqrt{\frac1n\sum_{i=1}^{n}(x_i-m)^2})^3}$</td><td>Zde odpovídá SKEW.P; SKEW má korekci.</td><td><a href="kapitola_03.html#sec-momenty">Výklad</a></td></tr>
<tr id="znak-g2"><th scope="row">$g_2$</th><td>Základní exces: kurtóza minus 3. Čtvrté mocniny průměrujeme a dělíme čtvercem rozptylu s dělením n.</td><td>$g_2=\frac{\frac1n\sum_{i=1}^{n}(x_i-m)^4}{(\frac1n\sum_{i=1}^{n}(x_i-m)^2)^2}-3$</td><td>KURT vrací korigovaný exces, nikoli přímo g₂.</td><td><a href="kapitola_03.html#sec-momenty">Výklad</a></td></tr>
<tr id="vztah-korekce-sikmosti"><th scope="row">Korigovaná šikmost</th><td>n je počet hodnot, g₁ základní momentový koeficient. Podmínky: alespoň 3 hodnoty a nenulová variabilita.</td><td>$\frac{\sqrt{n(n-1)}}{n-2}\,g_1$</td><td>Excel SKEW; základní SKEW.P korekci nepoužívá.</td><td><a href="kapitola_03.html#sec-momenty">Výklad</a></td></tr>
<tr id="vztah-korekce-excesu"><th scope="row">Korigovaný exces</th><td>n je počet hodnot, g₂ základní exces. Podmínky: alespoň 4 hodnoty a nenulová variabilita.</td><td>$\frac{n-1}{(n-2)(n-3)}[(n+1)g_2+6]$</td><td>Excel KURT; nejde o základní kurtózu ani základní g₂.</td><td><a href="kapitola_03.html#sec-momenty">Výklad</a></td></tr>
</tbody></table>
:::
